chore(CI): CI setup
torolocos/react-rtc pull request #11
Opened 2022-03-20 08:00 UTC by BrantalikP

- setup CODEOWNERS file - https://github.com/torolocos/react-rtc/issues/5
- setup Pull request template
- Install + setup Eslint and prettier
- setup TS and ESLINT CI checks
- Publishing is triggered only on new release

2022-03-21 05:57 UTC, pchalupa requested changes
Nice work! Also we could define Turbo pipelines https://turborepo.org/docs/features/pipelines to get linter running with turbo.

2022-03-21 05:57 UTC, pchalupa commented on packages/react-rtc/.editorconfig
> +# EditorConfig is awesome: https://EditorConfig.org
This config could be at the root of monorepo.

2022-03-21 05:57 UTC, pchalupa commented on packages/react-rtc/.eslintrc.js
> +module.exports = {
Could you please use JSON? https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-file-formats

2022-03-21 05:57 UTC, pchalupa commented on packages/react-rtc/package.json
> +    "eslint-config-google": "^0.14.0",
We should use just one of them.

2022-03-21 05:57 UTC, pchalupa commented on .github/workflows/npm-publish.yml
> +  release:
If `bump-version` workflow adds tag, then I think this could be on push.

2022-03-23 13:39 UTC, BrantalikP commented on .github/workflows/npm-publish.yml
> +  release:
keep push

2022-04-04 09:07 UTC, pchalupa approved these changes

2022-04-05 05:56 UTC, pchalupa approved these changes

2022-04-05 06:12 UTC, merged