wip: feat(WebExample
torolocos/react-rtc pull request #60
Opened 2022-08-03 13:18 UTC by BrantalikP

GH card ticket "link": #ADD LINK TO GITHUB TICKET OR ISSUE

### Description

(FILL IN SOME DESCRIPTION)

2022-08-03 13:23 UTC, pchalupa requested changes
Just minor thing. 🙌

2022-08-03 13:23 UTC, pchalupa commented on apps/web-example/src/features/auth/contexts/user.tsx
> +  const value = useMemo(
I think `useMemo` is not necessary. There is just one state `user`.

2022-08-03 13:46 UTC, pchalupa approved these changes

2022-08-03 14:05 UTC, merged

2022-08-04 12:51 UTC, lucasconstantino commented on apps/web-example/src/features/auth/contexts/user.tsx
> +};
Generally speaking, I hate the "pre-fill" strategy of contexts: setting a dummy value as default so to ensure the context is always available. Konstantin would probably disagree with me. But my take on the problem is to basically have the context value itself as `ContextValue | null`, defaulting to `null`, then having a usage hook handle the absence:

```ts
export const useUser = () => {
  const value = useContext(UserContext);
  
  if (!value) {
    throw new Error('Missing UserContext')
  }
  
  return value
};
```

2022-08-04 13:01 UTC, BrantalikP commented on apps/web-example/src/features/auth/contexts/user.tsx
> +};
Yes, totally agree with your approach. I've rushed up this and did not know if this will be even used. I'll re-review the whole code with the next PR and write it properly in the right form.